ups_web/ups/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', views.home, name='home'),
    path('trackPackage/',views.TrackPackageView,name='TrackPackageView'),
    path('registerUser/', views.RegisterUserView, name='RegisterUserView'),
    path('login/',auth_views.LoginView.as_view(template_name='ups/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('myPackages/',views.MyPackagesView,name='myPackages'),
    #path('package/<int:pk>',views.PackageDetailView.as_view(),name='package-detail'),
    path('package/<int:pk>', views.PackageDetail, name='package-detail'),
    #path('matchmypackage/',views.MatchMyPackageView,name = 'MatchMyPackageView')
    path('editmypackagedest/<int:package_id>',views.EditMyPackageDestView,name = 'EditMyPackageDestView'),
]

ups_web/ups_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView
urlpatterns = [
    path('',TemplateView.as_view(template_name='index.html'),name='home'),
    path('admin/', admin.site.urls),
    path('ups/', include('ups.urls')),
]

ups_web/ups/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
#from simple_history.models import HistoricalRecords
from django.urls import reverse
class World(models.Model):
    world_id = models.AutoField(primary_key=True)
    status = models.CharField(max_length=20,
                              default = 'OPEN',
                              null=False,
                              blank=False)
    speed = models.IntegerField(null=True)
    
    class Meta:
        db_table = 'world'

    def __str__(self):
        return str(self.world_id)

class UpsProfile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                unique=True,
                                related_name='profile')
    
    class Meta:
        db_table = 'ups_profile'

    def __str__(self):
        return self.user.__str__()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UpsProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    post_save.disconnect(save_user_profile, sender=User)
    instance.profile.save()
    post_save.connect(save_user_profile, sender=User)
                                    
    
class Truck(models.Model):
    #package = models.ForeignKey(Package, models.DO_NOTHING, primary_key=True)
    #world = models.ForeignKey('World', models.DO_NOTHING)
    world_id = models.IntegerField()
    truck_id = models.IntegerField(primary_key=True)
    x = models.IntegerField() #warehouse wh_x
    y = models.IntegerField() #warehouse wh_y
    
    TRUCK_STATUS_OP = (
        ('IDLE','IDLE'),
        ('EN ROUTE TO A WAREHOUSE','EN ROUTE TO A WAREHOUSE'),
        ('ARRIVED WAREHOUSE','ARRIVED WAREHOUSE'),
        ('DELIVERING','DELIVERING'),
        ('WAITING FOR PICKUP','WAITING FOR PICKUP'),
        ('INVAILD','INVAILD')
    )
    
    truck_status = models.CharField(max_length=50,
                                    choices = TRUCK_STATUS_OP,
                                    default = 'IDLE',
                                    #blank = True,
                                    null = True,
                                    help_text='Truck Status')
    #history = HistoricalRecords()
    class Meta:
        db_table = 'truck'

    def __str__(self):
        return str(self.truck_id)

class Package(models.Model):
    package_id = models.BigIntegerField(primary_key=True)
    #user = models.ForeignKey('UpsProfile',
                             #on_delete=models.CASCADE,
                             #null = True,blank = True,
                             #related_name="user_set")
    user_id = models.IntegerField(null = True)
    world_id = models.IntegerField()
    #world_id = models.ForeignKey('World', models.DO_NOTHING)
    #seqnum = models.IntegerField(null = False)
    truck = models.ForeignKey('Truck',models.DO_NOTHING,null=True)
    dep_x = models.IntegerField(help_text='Depature x')
    dep_y = models.IntegerField(help_text='Depature y')
    des_x = models.IntegerField(help_text='Destination x')
    des_y = models.IntegerField(help_text='Destination y')
    descp = models.TextField(null=True)
    count = models.IntegerField(null=True)

    '''
    item = models.CharField(max_length = 100,
                            default='Purchase from Amazon',
                            null = False,
                            blank=False)
    '''

    PACKAGE_STATUS_OP = (
        ('CREATED','CREATED'),
        ('TRUCK EN ROUTE TO WAREHOUSE','TRUCK EN ROUTE TO WAREHOUSE'),
        ('TRUCK WAITING FOR PACKAGE','TRUCK WAITING FOR PACKAGE'),
        ('OUT FOR DELIVERY','OUT FOR DELIVERY'),
        ('DELIVERED','DELIVERED')
    )
    
    package_status = models.CharField(max_length=50,
                                      choices = PACKAGE_STATUS_OP,
                                      blank = False,
                                      default = 'CREATED',
                                      null = False,
                                      help_text='Package Status')
    #history = HistoricalRecords()
    class Meta:
        db_table = 'package'

    def get_absolute_url(self):
        return reverse('package-detail',args=[str(self.package_id)])
        
    def __str__(self):
        return str(self.package_id)

class Product(models.Model):
    product_id = models.BigIntegerField(null = False)
    #package_id = models.IntegerField()
    package = models.ForeignKey(Package, on_delete=models.CASCADE,related_name='package_set')
    world = models.ForeignKey('World', models.DO_NOTHING)
    description = models.CharField(max_length=100,
                                   default='AProduct')
    count = models.IntegerField(null=False,default=1)
    #history = HistoricalRecords()
    class Meta:
        db_table = 'product'

    def get_absolute_url(self):
        return reverse('product-detail',args=[str(self.product_id)])

    def __str__(self):
        return self.description

    
class Shipment(models.Model):
    ship_id = models.BigIntegerField(primary_key=True)
    package = models.ForeignKey(Package, models.DO_NOTHING)
    world = models.ForeignKey('World', models.DO_NOTHING)
    #packing, packed, loading, loaded, delivering, delivered
    '''
    status = models.CharField(max_length=50,
                              default='Created')
    '''
    #history = HistoricalRecords()
    class Meta:
        db_table = 'shipment'

    def __str__(self):
        return str(self.ship_id)

class Shiplog(models.Model):
    package = models.ForeignKey('Package',models.DO_NOTHING)
    packagelog = models.TextField()
    world = models.ForeignKey('World',models.DO_NOTHING)

ups_web/ups/forms.py
from django import forms
from .models import UpsProfile
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Enter email',required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )
    '''
    def save(self, commit=True):
    user = UpsProfile.objects.create_user(
    self.cleaned_data['username'],
    self.cleaned_data['email'],
    self.cleaned_data['password1']
    )
    return user
    '''
class PackageMatchForm(forms.Form):
    package_id = forms.IntegerField(label = 'Your Package ID',required = True)

class EditPackageDestForm(forms.Form):
    des_x = forms.IntegerField(label = 'delivery dest x',required = True)
    des_y = forms.IntegerField(label = 'delivery dest y',required = True)

ups_web/ups/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.conf import settings
from django.http import HttpResponse
from django.db.models import Q
from ups.models import Package, Truck, World, Shiplog
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm,PackageMatchForm, EditPackageDestForm
from django.contrib.auth import login, authenticate
from .models import UpsProfile,Truck,Package,Shipment,Product
from django.contrib.auth.models import User
import socket
import pdb

host_ip = 'vcm-7989.vm.duke.edu'
port = 80

def connect_to_server(msg):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((host_ip, port))
    #msg = 'Hi Server!'
    s.send(msg.encode())
    s.close()

def index(request):
    return HttpResponse("Hello, world. You're at the UPS index.")

def home(request):
    return render(request, 'index.html')

def TrackPackageView(request):
    error = False
    if 'TrackingNumber'in request.GET:
        tracknum = request.GET['TrackingNumber']
        if not tracknum:
            error = True
        else:
            package_list = Package.objects.filter(package_id = tracknum)
            template = loader.get_template('ups/package_list.html')
            context = {
                'package_list' : package_list,
            }
            return HttpResponse(template.render(context, request))
    return render(request, 'ups/trackPackage.html')

def RegisterUserView(request):
    form = CustomUserCreationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'index.html')
    else:
        form = CustomUserCreationForm()            
    return render(request, 'ups/registerUser.html', {'form': form})

from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def MyPackagesView(request):
    #package_list = UpsProfile.objects.filter(user_id = request.user.pk).first().user_set.all()
    package_list = Package.objects.filter(user_id = request.user.pk)
    #print(request.user.pk)
    #pdb.set_trace()

    #print(package_list)
    #package_list = UpsProfile.objects.filter(pk = request.user.pk).first().package_set.all()
    #template = loader.get_template('ups/package_list.html')
    return render(request,'ups/myPackage_list.html',{'package_list':package_list})

def EditMyPackageDestView(request,package_id):
    mypackage = Package.objects.filter(package_id = package_id).filter(~Q(package_status = 'OUT FOR DELIVERY')).filter(~Q(package_status = 'DELIVERED')).first()
    #print("mypackage status")
    #print(mypackage.package_status)
    if mypackage is not None:
        if request.method=='POST':
            form = EditPackageDestForm(request.POST)
            if form.is_valid():
                des_x = form.cleaned_data['des_x']
                des_y = form.cleaned_data['des_y']
                mypackage.des_x = des_x
                mypackage.des_y = des_y
                mypackage.save()
                #prof = UpsProfile.objects.filter(pk = request.user.pk).first()
                #package = Package.objects.filter(package_id = package_id).first()
                #package.user = prof
                #package.save()
                return render(request,'ups/package_detail.html',{'package':mypackage})
                #return render(request, 'base_generic.html')
        else:
            form = EditPackageDestForm()
    else:
        return render(request, 'ups/error_page.html')
    return render(request,'ups/editMyPackageDest.html',{'form':form,'package_id':package_id})

'''
def MatchMyPackageView(request):
    if request.method=='POST':
        form = PackageMatchForm(request.POST)
        if form.is_valid():
            package_id = form.cleaned_data['package_id']
            prof = UpsProfile.objects.filter(pk = request.user.pk).first()
            package = Package.objects.filter(package_id = package_id).first()
            package.user = prof
            package.save()
            return render(request, 'base_generic.html')
    else:
        form = PackageMatchForm(request.POST)
    return render(request,'ups/match_my_package.html',{'form':form})
'''
'''
def QueryDeliveringTruckView(request,package_id):
    mypackage = Package.objects.filter(package_id = package_id).first()
    if request.method=='POST':
        print("test")
        connect_to_server(str(mypackage.truck.truck_id))
    #template = loader.get_template('ups/package_detail.html')
    #context ={
    #'current_states':True,
    #}
    return render(request,'ups/package_detail.html',{'pk': mypackage.pk})
'''

#@method_decorator(login_required, name='dispatch')
class PackageListView(generic.ListView):
    model = Package
    def get_queryset(self):
        return Package.objects.all()

'''    
>>>>>>> b0646558fb599bed545996e346de0a852c19af50
#@method_decorator(login_required, name='dispatch')
class PackageDetailView(generic.DetailView):
    model = Package
'''
#@login_required
def PackageDetail(request, pk):
    package = get_object_or_404(Package, pk=pk)
    world = World.objects.filter(status='OPEN').first()
    logs = Shiplog.objects.filter(package=package).filter(world=world)
    if package.truck_id is not None:
        truck = Truck.objects.get(pk=package.truck_id)
    else:
        truck = None
    world = World.objects.filter(status='OPEN').first()
    if truck:
        estimate=(abs(truck.x-package.des_x)+abs(truck.y-package.des_y))/(world.speed/1)
    else:
        estimate=None
    context = {
        'package': package,
        'truck': truck,
        'logs': logs,
        'estimate': estimate,
        'pk': pk,
    }
    return render(request, 'ups/PackageDetail.html', context)

ups_web/ups/templates/ups/PackageDetail.html
{% extends "base_generic.html" %}

{% block content %}
<style type="text/css">
#wrapper {
  width:1500px;
  clear:both;
  margin:0 auto;
  text-align:left;
  
}
#first {
  width:500px;
float:left;
}
#second {
  width:500px;
  float:left;
}
#third {
  width:500px;
  float:left;
}
</style>

<div id="wrapper">

  <div id="first">
    <h3>Package information</h3>
<p><strong>Package ID:</strong> {{ package.package_id }}</p>

<p><strong>Package Status:</strong> {{ package.get_package_status_display }}</p>
<!--p><strong>item:</strong> {{ package.package_set.description }}</p-->
<p><strong>Truck ID:</strong> {{ package.truck.truck_id }}</p>
<p><strong>Truck Status:</strong> {{ package.truck.get_truck_status_display }}</p>
<p><strong>Destination:</strong> ({{ package.des_x }}, {{package.des_y}})</p>
<p><strong>Description:</strong>{{package.descp}}</p>
<p><strong>Count:</strong>{{package.count}}</p>
<p><strong>Current Location:</strong>
  {% if package.package_status == 'OUT FOR DELIVERY' %}
  ({{truck.x}}, {{truck.y}})
  {% elif package.package_status == 'DELIVERED' %}
  ({{package.des_x}}, {{package.des_y}})
  {% else %}
  ({{package.dep_x}}, {{package.dep_y}})
  {% endif %}
</p>
{% if package.package_status == 'OUT FOR DELIVERY' and estimate %}
<p><strong>Estimate Arrive in</strong> {{estimate}} <strong>s</strong></p>
{% endif %}
<!--p><strong>Description:</strong> {{ package.package_set.description }}</p-->
<!--div style="margin-top:20px">
  <h4>Product</h4>
  {% for product in package.package_set.all %}
  <hr>
  <p><strong>Product Description:</strong>{{product.description}}</p>
  <p><strong>Product Count:</strong> {{product.count}}</p>
  {% endfor %}
<hr-->
</div>
<div id="second">
<h3>Tracking History</h3>
{% for log in logs%}
<p><strong>{{log.packagelog}}</strong></p>
{% endfor %}
</div>
<div id="third">
{% if package.package_status != 'OUT FOR DELIVERY' and package.package_status != 'DELIVERED' %}
<p>Want to change the delivery destination?</p>
<p>Go ahead and click the button below!</p>
<form class="form-inline ml-auto">
  <a href="{% url 'EditMyPackageDestView' package.package_id %}" class="btn btn-outline-secondary">Edit Delivery Destination</a>
</form>
{% else %}
<p>Your package has been shipped!</p>
<p>You cannot change delivery destination of this package.</p>
<p>Please click the button below to check other packages.</p>
<form class="form-inline ml-auto">
  <a href="{% url 'myPackages' %}" class="btn btn-outline-secondary">Check My Package List</a>
</form>
{% endif %}
</div>
</div>
{% endblock %}
  

ups_web/ups/templates/ups/editMyPackageDest.html
{% extends 'base_generic.html' %}

{% block content %}
<form action= "/ups/editmypackagedest/{{package_id}}"  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-secondary" value="Save">
</form>
{% endblock %}

ups_web/ups/templates/ups/error_page.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Sorry You cannot change delivery destination of this package!</h1>
<p>Your package has been shipped!</p>
<p>Please click the button below to check other packages.</p>
<form class="form-inline ml-auto">
  <a href="{% url 'myPackages' %}" class="btn btn-outline-secondary">Check My Package List</a>
</form>


{% endblock %}

ups_web/ups/templates/ups/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Welcome to Mini UPS!</h1>
{% endblock %}

ups_web/ups/templates/ups/login.html
{% extends 'base_generic.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h1 class="text-center logo my-4">
    <a style="color:#212529;" href="{% url 'home' %}">Mini UPS</a>
  </h1>
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
	<div class="card-body">
	  <h3 class="card-title">Log in</h3>
	  <form method="post" novalidate>
	    {% csrf_token %}
	    {% include 'includes/form.html' %}
	    <button type="submit" class="btn btn-outline-info btn-block">Log in</button>
	  </form>
	</div>
	<div class="card-footer text-muted text-center">
	  New to UPS? <a style="color:#212529;" href="{% url 'RegisterUserView' %}">Sign up</a>
	</div>
      </div>
      <div class="text-center py-2">
	<small>
	  <!--a href="#" class="text-muted">Forgot your password?</a-->
	</small>
      </div>
    </div>
  </div>
</div>
{% endblock %}

ups_web/ups/templates/ups/match_my_package.html
{% extends 'base_generic.html' %}

{% block content %}
<form action= "/ups/matchmypackage/"  method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>
{% endblock %}

ups_web/ups/templates/ups/myPackage_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Your Packages</h1>

{% if package_list %}
<ul>
  {% for package in package_list %}
  <p ><a  style="color: #212529" href="{{ package.get_absolute_url }}">Package: {{package.package_id}} </a></li>
  {% endfor %}
</p>
  <!--p>Did not see your package in the list?</p>
  <p>Add your package to your account!</p>
  <form class="form-inline ml-auto">
    <a href="/ups/matchmypackage/" class="btn btn-outline-secondary">Add Package Record</a>
  </form-->

{% else %}
<p>Currently,</p>
<p>There is no package information under your account.</p>
<p>You may click the button on top left to go to the UPS home page.</p>
{% endif %}
{% endblock %}

ups_web/ups/templates/ups/package_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Your Package is Here !</h1>

<p><strong>Package ID:</strong> {{ package.package_id }}</p>

<p><strong>Package Status:</strong> {{ package.get_package_status_display }}</p>
<!--p><strong>item:</strong> {{ package.package_set.description }}</p-->
<p><strong>Truck ID:</strong> {{ package.truck.truck_id }}</p>
<p><strong>Truck Status:</strong> {{ package.truck.get_truck_status_display }}</p>
<p><strong>Destination x:</strong> {{ package.des_x }}</p>
<p><strong>Destination y:</strong> {{ package.des_y }}</p>
<p><strong>Description:</strong>{{package.descp}}</p>
<p><strong>Count:</strong>{{package.count}}</p>
<!--p><strong>Description:</strong> {{ package.package_set.description }}</p-->
<!--div style="margin-top:20px">
  <h4>Product</h4>
  {% for product in package.package_set.all %}
  <hr>
  <p><strong>Product Description:</strong>{{product.description}}</p>
  <p><strong>Product Count:</strong> {{product.count}}</p>
  {% endfor %}
<hr-->

{% if package.package_status != "OUT FOR DELIVERY" and package.package_status != "DELIVERED" %}
<p>Want to change the delivery destination?</p>
<p>Go ahead and click the button below!</p>
<form class="form-inline ml-auto">
  <a href="{% url 'EditMyPackageDestView' package.package_id %}" class="btn btn-outline-secondary">Edit Delivery Destination</a>
</form>
{% else %}
<p>Your package has been shipped!</p>
<p>You cannot change delivery destination of this package.</p>
<p>Please click the button below to check other packages.</p>
<form class="form-inline ml-auto">
  <a href="{% url 'myPackages' %}" class="btn btn-outline-secondary">Check My Package List</a>
</form>
{% endif %}
{% endblock %}
  

ups_web/ups/templates/ups/package_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Delivery Detail</h1>

{% if package_list %}
<ul>
  {% for package in package_list %}
  <li>
    <a href="{{ package.get_absolute_url }}">Package: {{package.package_id}} </a>
  </li>
  {% endfor %}

</ul>
{% else %}
<p>Please correct the following errors</p>
<p>The tracking number you entered is not valid. Please review or contact the sender to verify the number.</p>
<form action= "/ups/trackPackage/"  method="get">
  <input type="submit" class="btn btn-outline-info" value="Back To Tracking">
</form>
{% endif %}
{% endblock %}

ups_web/ups/templates/ups/registerUser.html
{% extends 'base_generic.html' %}


{% block content %}

<div class="login">
  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  <h1>Sign Up For UPS Now!</h1>
  <form method="post" >
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
	<td></td>
	<td><input type="submit" class="btn btn-outline-info" name="submit" value="Register" /></td>
      </tr>
    </table>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Already Have An Account? <a class="ml-2" href="">Sign In</a>
  </small>
</div>
{% endblock %}

ups_web/ups/templates/ups/trackPackage.html
{% extends 'base_generic.html' %}

{% block content %}
<style type="text/css">
#wrapper {
  width:800px;
  clear:both;
  margin:0 auto;
  text-align:center;
</style>
<div id="wrapper">
   <form action= "/ups/trackPackage/"  method="get">
     {% csrf_token %}
     <p>Please enter tracking number:</p>
     <td><input type="text" name="TrackingNumber"> </td>
     <br>
     <br>
     <input type="submit" class="btn btn-outline-info" value="Tracking">
   </form>
</div>
 {% endblock %}